### ISSUE TITLE
Error when using AutoWCS on manually supplied catalog: Could not find BINTABLE with name 'GaiaDR3'

### ISSUE THREAD

**Issue by EAlexJ** [user29A/CCDLAB#3]
When starting the AutoWCS with a manually supplied catalog the following error gets thrown:
![image](https://user-images.githubusercontent.com/97940321/235240748-fecfb1c8-f470-422e-bbfe-465224968718.png)
Is this an error caused by supplying a bad file? The file is obtained by using AstroCarta manually, if it is a bad file how does the query need to be structured to create a resulting catalog excerpt that can be used?
Thank you for your help!

**Comment by user29A** [comment]
Here is a video tutorial which should still be mostly accurate:

https://www.youtube.com/watch?v=4_48yRcN3nc

Python is not required any longer as I've coded the astro query in C# now.

If you used AstraCarta manually, then you will need to point the WCS to the file. In the textbox above the WCS->AstraCarta, where it says "File:", if you click there then it will give you a file dialog to with which you can point to the file which AstraCarta downloaded. If you use the WCS->AstraCarta interface, then it will put the file name automatically into that textbox field.

**Comment by EAlexJ** [comment]
Hello Joe,
this is the command I am using to invoke the query:
`% astracarta -ra 328.699 -dec -53.194 -scale 0.158 -pixwidth 1897 -pixheight 1946 -buffer 0.5`
I then use the generated outputfile to use as a catalogue for AutoWCS.

Note that when using a fullstop in the scale setting, meaning `0.155` instead of `0,155` I get thrown an error that there is a problem with the initial scale setting.

I managed to resolve the error above, by adding a name to the extension in the fits file. Here is how I did it:
```
from astropy.io import fits

# Open the FITS file
hdul = fits.open('your_file.fits', mode='update')

# Assign a name to the extension
hdul[1].header['EXTNAME'] = 'MY_EXTENSION_NAME'

# Save the modified FITS file
hdul.flush()

# Close the FITS file
hdul.close()
```
When opening the Catalogue tab the Extension name gets recognized automatically.

I suggest that astracarta adds an extensioname by itself.
