### ISSUE TITLE
Missing references when building CCDLAB solution

### ISSUE THREAD

**Issue by EAlexJ** [user29A/CCDLAB#5]
In order to try to find and solve for the bugs I encountered so far using the software, I think it is more practical to give debugging it by myself a try.

I downloaded the source code provided and tried building the project, however it does not seem to be setup to manage the dependencies of references by itself. The four missing dependencies are: JPChart, JPFITS, MLCCDLAB and MWArray. From the csproj file I can see that the last two are originally from Matlab, which is also not currently installed on my machine.

Do you have a build system in use that could be adapted in order to allow out of the box building of the CCDLAB project?  It does not seem feasible to manage the dependencies by hand since for example the JPCharts project also does not provide dependency management and relies on other packages.

I have little experience with build processes in VisualStudio and C# but in case you dont either, I am certain I will manage to get a working solution and share it with you.

Thanks in Advance,
Eyck

**Comment by user29A** [comment]
If you've installed CCDLAB those dependencies will be in the installation folder, and you can just copy them from there. Just put them in a folder beside the CCDLAB folder, and reference them, etc.

**Comment by EAlexJ** [comment]
I went into the .csproj file and modified the references like this:
```
  <Reference Include="JPChart, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\Program Files\Astrowerks\CCDLAB\JPChart.dll</HintPath>
    </Reference>
```
I changed the Hint Paths for all the missing references and it now builds without a problem.

Thanks for the help!
