### ISSUE TITLE
Error when refining initial solution

### ISSUE THREAD

**Issue by EAlexJ** [user29A/CCDLAB#6]
Hi Joe,
I managed to get the WCS Solution working, it is lightning fast and the results seem very good accuracy wise aswell!

When running AutoWCS the "Finished" dialog box opens, and I get asked to refine the solution. As you already mentioned, flipping the image was necessary to get the solution at all.

When agreeing, the following error gets thrown:
![image](https://github.com/user29A/CCDLAB/assets/97940321/191f9309-3d28-4852-8a77-e6d15f367d62)

This is done on the r filter I shared with you recently.

Edit: I get the exact same error when trying to get any solution on the g filter

**Comment by user29A** [comment]
Hi Eyck,

I can't quite tell from that message what the error is.  You can try unchecking the option to refine, or, just tell it "no". Ensure that "500" is the Number of Source Points in the option to refine.

![refine](https://github.com/user29A/CCDLAB/assets/40668405/0cdc0342-4819-4d24-85d7-59f17d831a24)

**Comment by EAlexJ** [comment]
I made sure that the number is set to 500, the error still persist.

I get the same error when trying for any solution (flipped and not flipped) with this [file](https://drive.google.com/file/d/1lmHRFXrCbeGyxzP8VN8xCVJ1ZZO0TmZV/view?usp=drive_link). This is not the only file where this error occurs, I have quite some more that throw the same error.

**Comment by user29A** [comment]
It is so strange.

Show me all of the settings in the WCS menu like my screen shot above. Also take a screenshot of the PSE Tab from the tab control on the upper right of CCDLAB.

**Comment by EAlexJ** [comment]
Here is the full screen after finding the initial solution, including the PSE tab:

![CCDLAB_error_1](https://github.com/user29A/CCDLAB/assets/97940321/313cccd6-212a-4d5d-9ae0-4bec29917d83)

Here the error when clicking on yes:
![CCDLAB_error_2](https://github.com/user29A/CCDLAB/assets/97940321/08bc01d3-e256-4393-862c-2eb258cc4d9e)

And the settings of the WCS menu:
![CCDLAB_error_3](https://github.com/user29A/CCDLAB/assets/97940321/2eebf13f-5f68-4b56-a39d-0fc35cdce14e)

**Comment by user29A** [comment]
Okay, I do see a problem with some settings, which might be left-over from when CCDLAB was installed with the previous language settings which did not read the registry settings correctly.

On the PSE tab control on the upper right of the CCDLAB main window, there is a numeric up-down control for "Src Separation" (source separation) and one for "Kernel Radius". The values they have of 1 and 5 should not be possible, and should be consistent with throwing an index out of range error...so hopefully that is the cause.

Please change 'Src Separation' to 25, and 'Kernel Radius' to 10. 

Then try again. Let me know what happens!

**Comment by EAlexJ** [comment]
I decided to completely reinstall the software, to have a fresh Installation with the correct Format Settings. This seemed to have solved the issue, I am now finding solutions consistently.
Thank you for your help!
